CREATE TABLE [dbo].[Hashtags]
(
	[id] INT NOT NULL IDENTITY,
	[UID] INT NOT NULL,
	[HASHTAG] NVARCHAR(100) NOT NULL,
	[TOWN] NVARCHAR(100) NOT NULL,
    CONSTRAINT [PK_Hashtags] PRIMARY KEY ([id]), 
    CONSTRAINT [FK_Hashtags_ToEvent] FOREIGN KEY ([UID]) REFERENCES [User]([id]) 
)
